### ISSUE TITLE
How can I compile

### ISSUE THREAD

**Issue by fozbek** [DOSexample/SkyCore#1]
Hi, I want to compile this but I don't know how to. What components do I need? Do I need VS 2022?
I am a PHP developer that is why I am not familiar with this.

**Comment by fozbek** [comment]
I changed the 'Platform Toolset' to 'Visual Studio 2022 (v143)'. and I have succeeded to compile.
Can you help me about 12sky2 client? I could not find any of it. Can you share the client? Or can you help me about it? @DOSexample

**Comment by DOSexample** [comment]
it's not a complete server
